# Generated by Django 5.0.7 on 2025-09-26 18:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('telegram_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('name', models.CharField(default='', max_length=255)),
                ('phone', models.CharField(default='', max_length=20, unique=True)),
                ('date_registered', models.DateField(default=django.utils.timezone.now)),
                ('weeks_pregnant', models.PositiveIntegerField(default=0, help_text='Number of weeks pregnant')),
                ('ward', models.CharField(default='', max_length=100)),
                ('county', models.CharField(default='', max_length=100)),
                ('emergency_contact', models.CharField(blank=True, help_text='Hospital phone number', max_length=20)),
                ('current_week', models.PositiveIntegerField(default=0, help_text='Auto-calculated pregnancy week', null=True)),
                ('status', models.CharField(default='good', help_text='Pregnancy visit status', max_length=20, null=True)),
                ('preferred_hospitals', models.ManyToManyField(blank=True, related_name='preferred_patients', to='hospital.hospital')),
                ('suggested_hospitals', models.ManyToManyField(blank=True, related_name='suggested_patients', to='hospital.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('missed', 'Missed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='hospital.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='wa_patient.patient')),
            ],
        ),
    ]
