# Generated by Django 5.2.6 on 2025-09-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wa_patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='current_week',
            field=models.PositiveIntegerField(default=0, help_text='Auto-calculated pregnancy week', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(default='good', help_text='Pregnancy visit status', max_length=20, null=True),
        ),
    ]
