# Generated by Django 5.2.6 on 2025-09-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wa_patient', '0002_alter_patient_current_week_alter_patient_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
