# Generated by Django 5.2.6 on 2025-09-24 17:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
        ('wa_patient', '0002_remove_patient_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='preferred_hospital',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='signup_date',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
        migrations.AddField(
            model_name='patient',
            name='county',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='date_registered',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact',
            field=models.CharField(blank=True, help_text='Hospital phone number', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='preferred_hospitals',
            field=models.ManyToManyField(blank=True, related_name='preferred_patients', to='hospital.hospital'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='suggested_hospitals',
            field=models.ManyToManyField(blank=True, related_name='suggested_patients', to='hospital.hospital'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ward',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='weeks_pregnant',
            field=models.PositiveIntegerField(default=0, help_text='Number of weeks pregnant'),
        ),
    ]
