# Generated by Django 5.1.6 on 2025-09-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wa_patient', '0003_rename_full_name_patient_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='id_number',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
