# Generated by Django 5.0.7 on 2025-09-26 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wa_patient', '0004_patient_id_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='id_number',
        ),
    ]
